object frmRecipes: TfrmRecipes
  Left = 0
  Top = 0
  BorderStyle = bsToolWindow
  Caption = 'Recipes'
  ClientHeight = 193
  ClientWidth = 288
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnDeactivate = FormDeactivate
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 13
end
