{$IF DEFINED(GENERIC)}
  {$IFDEF DELEGATE1} E1{$ENDIF}
  {$IFDEF DELEGATE2},E2{$ENDIF}
  {$IFDEF DELEGATE3},E3{$ENDIF}
  {$IFDEF DELEGATE4},E4{$ENDIF}
  {$IFDEF DELEGATE5},E5{$ENDIF}
  {$IFDEF DELEGATE6},E6{$ENDIF}
  {$IFDEF DELEGATE7},E7{$ENDIF}
  {$IFDEF DELEGATE8},E8{$ENDIF}
{$ELSEIF DEFINED(PARAMS)}
  {$IFDEF DELEGATE1} AParam1: E1{$ENDIF}
  {$IFDEF DELEGATE2};AParam2: E2{$ENDIF}
  {$IFDEF DELEGATE3};AParam3: E3{$ENDIF}
  {$IFDEF DELEGATE4};AParam4: E4{$ENDIF}
  {$IFDEF DELEGATE5};AParam5: E5{$ENDIF}
  {$IFDEF DELEGATE6};AParam6: E6{$ENDIF}
  {$IFDEF DELEGATE7};AParam7: E7{$ENDIF}
  {$IFDEF DELEGATE8};AParam8: E8{$ENDIF}
{$ELSEIF DEFINED(CALL)}
  {$IFDEF DELEGATE1} AParam1{$ENDIF}
  {$IFDEF DELEGATE2},AParam2{$ENDIF}
  {$IFDEF DELEGATE3},AParam3{$ENDIF}
  {$IFDEF DELEGATE4},AParam4{$ENDIF}
  {$IFDEF DELEGATE5},AParam5{$ENDIF}
  {$IFDEF DELEGATE6},AParam6{$ENDIF}
  {$IFDEF DELEGATE7},AParam7{$ENDIF}
  {$IFDEF DELEGATE8},AParam8{$ENDIF}
{$ENDIF}
